import {
  LedgerAccountStatementItems,
  LedgerStatementAprItems,
  LedgerStatementItems,
} from './types';

export const ledgerStatementsItems: LedgerStatementItems = {
  statements: [
    {
      id: 1,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 1,
      balance_close: 1,
      repayment_minimum_amount_due: 1,
      repayment_status: 'R',
      account_alias: '0001',
      institution_id: 1,
      product_name: 'Test product name',
      first_name: 'John',
      last_name: 'Jones',
      account_alias_additional: 'test',
      address_line1: 'test',
      address_line2: 'test',
      address_line3: 'test',
      address_line4: 'test',
      address_town: 'test',
      address_post_code: 'test',
      address_country_code: 'test',
      previous_statement_id: 1,
    },
    {
      id: 2,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 2,
      balance_close: 2,
      repayment_minimum_amount_due: 2,
      repayment_status: 'R',
      account_alias: '0001',
      institution_id: 1,
      product_name: 'Test product name',
      first_name: 'John',
      last_name: 'Jones',
      account_alias_additional: 'test',
      address_line1: 'test',
      address_line2: 'test',
      address_line3: 'test',
      address_line4: 'test',
      address_town: 'test',
      address_post_code: 'test',
      address_country_code: 'test',
      previous_statement_id: 1,
    },
  ],
};

export const ledgerAccountStatementsItems: LedgerAccountStatementItems = {
  statements: [
    {
      id: 1,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 1,
      balance_close: 1,
      repayment_minimum_amount_due: 1,
      repayment_status: 'R',
      accrued_interest_total: 1.00,
      start_date: '07/10/2019',
      repayment_type: null,
    },
    {
      id: 2,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 1,
      balance_close: 1,
      repayment_minimum_amount_due: 1,
      repayment_status: 'O',
      accrued_interest_total: 1.00,
      start_date: '07/10/2019',
      repayment_type: null,
    },
  ],
};

export const ledgerAccountStatementAprItems: LedgerStatementAprItems = {
  statement_aprs: [
    {
      statement_id: 1,
      product_apr_id: 1,
      accrued_interest: 1,
      description: 'Description',
      rate: 1,
    },
  ],
};
