import { LedgerStatementItems } from './types';

export const ledgerStatementsItems: LedgerStatementItems = {
  response_status: {
    status_code: 0,
  },
  statements: [
    {
      id: 1,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 1,
      balance_close: 1,
      minimum_amount_due_repayment: 1,
      statement_cycle_id: 1,
      cycle_execution_history_id: 1,
      account_alias: '0001',
      institution_id: 1,
      product_name: 'Test product name',
      first_name: 'John',
      last_name: 'Jones',
      statement_cycle_description: '',
    },
    {
      id: 2,
      account_id: 1,
      first_transaction_id: 2,
      last_transaction_id: 23,
      statement_date: '07/10/2019',
      balance_open: 2,
      balance_close: 2,
      minimum_amount_due_repayment: 2,
      statement_cycle_id: 2,
      cycle_execution_history_id: 2,
      account_alias: '0001',
      institution_id: 1,
      product_name: 'Test product name',
      first_name: 'John',
      last_name: 'Jones',
      statement_cycle_description: '',
    },
  ],
};
