export const detailsInitialFormValues = {
  apr: '0.00',
  aprDefault: '0.00',
  feeExceedLimit: '0.00',
  feeLatePayment: '0.00',
  feeOverpayment: '0.00',
  minimumPaymentAmount: '0.00',
  minimumPaymentRate: '0.00',
  rateExceedLimit: '0.00',
  rateLatePayment: '0.00',
  rateOverpayment: '0.00',
  maximumDepositAllowed: '0.00',
  maximumMonthlyDeposit: '0.00',
  minimumDepositAllowed: '0.00',
  aprOverdraft: '0.00',
};
