export { default as ProductDetails } from './ProductDetails';
export { default as ProductGeneralInfo } from './ProductGeneralInfo';
export { default as ProductRules } from './ProductRules';
export { default as ProductAuxiliaryCounters } from './ProductAuxiliaryCounters';
export { default as ProductAprs } from './ProductAprs';
export { default as ProductLoyaltyAndBonus } from './ProductLoyaltyAndBonus';
export { default as  Services } from './ProductServices';
export { default as AprsTable } from './AprsTable';
export { default as GeneralLedger } from './GeneralLedger';
export * from './tableColumns';
