export { default as ProductDetails } from './ProductDetails';
export { default as ProductGeneralInfo } from './ProductGeneralInfo';
export { default as ProductRules } from './ProductRules';
export { default as ProductAuxiliaryCounters } from './ProductAuxiliaryCounters';
export { default as ProductAprs } from './ProductAprs';
export { default as ProductFees } from './ProductFees';
export { default as ProductRewards } from './ProductRewards';
export { default as  Services } from './ProductServices';
export { default as AprsTable } from './AprsTable';
export { default as FeesTable } from './FeesTable';
export { default as RewardsTable } from './RewardsTable';
export { default as GeneralLedger } from './GeneralLedger';
export { default as IllustrationLoan } from './ProductIllustrationLoan';
export * from './tableColumns';
