import {
  IDirectDebitPaymentHistoryData,
  ISettleTransactionDataReq,
  ITransactionsData,
} from './types';

/** Transactions mock */
export const transactionsMock: ITransactionsData = {
  transactions: [
    {
      id: 1,
      account_id: 1,
      institution_id: 1,
      amount: 10,
      amount_in_original_currency: 10.2,
      balance_authorised_after: 20,
      balance_authorised_before: 10,
      balance_settled_after: 10,
      balance_settled_before: 10,
      card_acceptor_location: null,
      card_acceptor_name: null,
      card_amount: null,
      card_conversion_rate: null,
      card_currency: null,
      card_id: null,
      card_transaction_id: null,
      debit_credit_indicator: 'D',
      description: 'Mock record',
      original_currency: 'GBP',
      transaction_datetime: '11/08/2019 00:04:46',
      transaction_type_id: 1,
      status: 'P',
      settled_date: null,
      amount_settled: 0,
      source_endpoint_id: 1,
      transaction_type_description: 'Purchase card',
      product_apr_id: 1,
      product_fee_id: 2,
      product_reward_id: 1,
      apr_rate: 5,
      fee_rate: 0.3,
      fee_amount: 3,
      fee_application_condition: 'A',
      apr_calculation_method: 'A',
      reward_application_condition: 'S',
      reward_rate: 0.05,
      reward_amount: 1,
      card_currency_billing: null,
      card_amount_billing: null,
      card_acceptor_terminal_id: null,
      card_acceptor_id_code: null,
      card_stan: null,
      card_mcc: null,
      card_acquirer_id: null,
      card_acquirer_country_code: null,
      card_pos_entry_mode: null,
      card_pos_condition_data: null,
      card_response_code: null,
      parent_transaction_id: null,
    },
  ],
};

export const directDebitPaymentMock: IDirectDebitPaymentHistoryData = {
  payment: [
    {
      id: 2,
      transaction_id: 1234,
      mandate_id: 123,
      provider_timestamp: '17/06/2019 00:00:00',
      amount: 10,
      status: 'Submitted',
      account_alias: '9438',
      bank_name: 'National Westminster Bank (NatWest)',
    },
    {
      id: 3,
      transaction_id: 1234,
      mandate_id: 123,
      provider_timestamp: '18/06/2019 00:00:00',
      amount: 10,
      status: 'Verified',
      account_alias: '9438',
      bank_name: 'National Westminster Bank (NatWest)',
    },
    {
      id: 4,
      transaction_id: 1234,
      mandate_id: 123,
      provider_timestamp: '19/06/2019 00:00:00',
      amount: 10,
      status: 'Completed',
      account_alias: '9438',
      bank_name: 'National Westminster Bank (NatWest)',
    },
    {
      id: 1,
      transaction_id: 1234,
      mandate_id: 123,
      provider_timestamp: '16/06/2019 00:00:00',
      amount: 10,
      status: 'Pending',
      account_alias: '9438',
      bank_name: 'National Westminster Bank (NatWest)',
    },
  ],
};

/** Settle transaction mock */
export const settleTransactionMock: ISettleTransactionDataReq = {
  transaction: [
    {
      transaction_id: 3456,
      amount_settled: 1,
      settled_date: '2020-01-08 22:55:12',
    },
  ],
};
