export enum formNamesConst {
  USER_LOGIN = 'userLoginForm',
  LOGIN_CODE = 'loginCodeForm',
  PASSWORD = 'passwordForm',
  CHANGE_PROFILE = 'changeProfileForm',
  CHANGE_PASSWORD = 'changePasswordForm',

  SETTLE_TRANSACTION_FORM = 'settleTransactionForm',
  TRANSACTION_RETRIEVING_FORM = 'transactionRetrievingForm',

  FILTER = 'filterForm',

  PRODUCT = 'productForm',
  ADD_PRODUCT = 'addProductForm',
  GENERAL_PRODUCT = 'generalProductForm',
  PRODUCT_DETAILS = 'productDetailsForm',
  PRODUCT_RULES = 'productRulesForm',
  PRODUCT_LIMITS_AND_COMMISSION = 'productLimitsFeesAndCommissionsForm',
  PRODUCT_AUXILIARY_COUNTERS = 'productAuxiliaryCountersForm',
  PRODUCT_SERVICES = 'productServicesForm',
  PRODUCT_APRS = 'productAprsForm',
  PRODUCT_FEES = 'productFeesForm',
  PRODUCT_REWARDS = 'productRewardsForm',
  PRODUCT_LOYALTY_AND_BONUS = 'productLoyaltyAndBonus',
  PRODUCT_GENERAL_LEDGER = 'productGeneralLedger',
  PRODUCT_ILLUSTRATION_FORM = 'productIllustrationForm',

  USERS_GROUP = 'usersGroupForm',
  ADD_USERS_GROUP = 'addUsersGroupForm',
  EDIT_USERS_GROUP = 'editUsersGroupForm',
  EDIT_USERS_GROUP_MEMBERS = 'editUsersGroupMembersForm',
  ADD_USERS_GROUP_PERMISSIONS = 'addUsersGroupPermissionsForm',
  USER = 'userForm',

  ENDPOINT = 'endpointsForm',
  INTERFACE = 'interfaceForm',
  INSTITUTION = 'institutionForm',
  ADD_SYSTEM_PROPERTY = 'addSystemPropertyForm',

  SCHEDULER = 'schedulerForm',
  GENERATE_CRON_EXPRESSION = 'generateCronExpressionForm',

  API_CALL = 'apiCallForm',

  CUSTOMER = 'customerForm',
  CURRENCY_LIMIT = 'currencyLimit',
  REPAYMENT_DEBIT_CARDS = 'repaymentDebitCardsForm',
  REPAYMENT_DIRECT_DEBITS = 'repaymentDirectDebitsForm',
  ACCOUNT = 'accountForm',
  TRANSACTION = 'transactionForm',
  MANUAL_TRANSACTION = 'manualTransaction',
  RESULT_MANUAL_TRANSACTION = 'resultManualTransaction',
  RESULT_LIMIT_ADJUSTMENT = 'limitAdjustment',
  CARD = 'cardForm',
  ACCOUNT_CARDS = 'accountCardsForm',
  STATEMENT = 'statementForm',
  CHANGE_CARD_STATUS = 'changeCardStatus',
}
