export enum formNamesConst {
  USER_LOGIN = 'userLoginForm',
  LOGIN_CODE = 'loginCodeForm',
  PASSWORD = 'passwordForm',
  CHANGE_PROFILE = 'changeProfileForm',
  CHANGE_PASSWORD = 'changePasswordForm',

  SETTLE_TRANSACTION_FORM = 'settleTransactionForm',
  TRANSACTION_RETRIEVING_FORM = 'transactionRetrievingForm',

  FILTER = 'filterForm',

  PRODUCT = 'productForm',
  ADD_PRODUCT = 'addProductForm',
  GENERAL_PRODUCT = 'generalProductForm',
  PRODUCT_DETAILS = 'productDetailsForm',
  PRODUCT_RULES = 'productRulesForm',
  PRODUCT_LIMITS_AND_COMMISSION = 'productLimitsFeesAndCommissionsForm',
  PRODUCT_AUXILIARY_COUNTERS = 'productAuxiliaryCountersForm',
  PRODUCT_SERVICES = 'productServicesForm',
  PRODUCT_APRS = 'productAprsForm',
  PRODUCT_FEES = 'productFeesForm',
  PRODUCT_REWARDS = 'productRewardsForm',
  PRODUCT_LOYALTY_AND_BONUS = 'productLoyaltyAndBonus',
  PRODUCT_GENERAL_LEDGER = 'productGeneralLedger',
  PRODUCT_ILLUSTRATION_FORM = 'productIllustrationForm',

  ADD_USER_GROUP = 'addUserGroupForm',
  EDIT_GENERAL_INFO_USER_GROUP = 'editGeneralInfoUserGroupForm',
  EDIT_USER_GROUP_MEMBERS = 'editUserGroupMembersForm',
  EDIT_GROUP_PERMISSION = 'editGroupPermissionForm',
  USERS_GROUP = 'usersGroupForm',
  ADD_GROUP_PERMISSIONS = 'addGroupPermissions',
  DEFINE_USER = 'defineUserForm',

  ENDPOINT = 'endpointsForm',
  INTERFACE = 'interfaceForm',
  INSTITUTIONS = 'institutionsForm',
  ADD_SYSTEM_PROPERTY = 'addSystemPropertyForm',

  DEFINE_SCHEDULER_JOB = 'defineSchedulerJobForm',
  GENERATE_CRON_EXPRESSION = 'generateCronExpression',

  AUDIT_API_CALL = 'auditApiCallForm',

  LEDGER_CUSTOMER = 'ledgerCustomerForm',
  LEDGER_REPAYMENT_DEBIT_CARDS = 'ledgerRepaymentDebitCardsForm',
  LEDGER_REPAYMENT_DIRECT_DEBITS = 'ledgerRepaymentDirectDebitsForm',
  LEDGER_ACCOUNT = 'ledgerAccountForm',
  LEDGER_TRANSACTION = 'ledgerTransactionForm',
  LEDGER_MANUAL_TRANSACTION = 'ledgerManualTransaction',
  LEDGER_RESULT_MANUAL_TRANSACTION = 'ledgerResultManualTransaction',
  LEDGER_RESULT_LIMIT_ADJUSTMENT = 'ledgerLimitAdjustment',
  LEDGER_CARDS = 'ledgerCardForm',
  LEDGER_ACCOUNT_CARDS = 'ledgerAccountCardsForm',
  LEDGER_STATEMENT = 'ledgerStatementForm',
  LEDGER_CHANGE_CARD_STATUS = 'ledgerChangeCardStatus',
}
