export enum iconNamesConst {
  ARROW_DOWN = 'arrowDown',
  ARROW_UP = 'arrowUp',
  DELETE = 'delete',
  DOWNLOAD = 'download',
  EDIT = 'edit',
  FILE = 'file',
  FILE_PDF = 'filePdf',
  FILTER = 'filter',
  KEY = 'key',
  LOAN = 'loan',
  LOCK = 'lock',
  LOGOUT = 'logOut',
  PLUS = 'plus',
  QRCODE = 'qrcode',
  REFRESH = 'refresh',
  SEARCH = 'search',
  SHORT_TEXT = 'shortText',
  SMARTPHONE = 'smartphone',
  STOP = 'stop',
  USER = 'user',
}
