export enum modalNames {
  ADD_ADMIN_ACTIVE_USER = 'AddAdminActiveUser',
  ADD_ADMIN_USERS_GROUP = 'AddAdminUsersGroupModal',
  EDIT_ADMIN_USERS_GROUP = 'EditAdminUsersGroupModal',
  MESSAGE_MODAL = 'MessageModal',
  CONFIRMATION_MODAL = 'ConfirmationModal',
  ADD_ADMIN_CYCLE_EDITOR = 'AddAdminCycleEditorModal',
  EDIT_CYCLE_EDITOR = 'EditCycleEditorRecordsModal',
  ADD_ADMIN_SYSTEM_PROPERTY = 'AddAdminSystemPropertyModal',
  ADD_PRODUCT = 'AddProductModal',
  EDIT_PRODUCT = 'EditProductModal',
  ADD_ADMIN_SCHEDULER = 'AddAdminSchedulerModal',
  EDIT_ADMIN_SCHEDULER = 'EditAdminSchedulerModal',
  ADD_ADMIN_USER = 'AddAdminUserModal',
  EDIT_ADMIN_USER = 'EditAdminUserModal',
}
