export enum uiItemConsts {
  ADMINISTRATION_DICTIONARIES_COUNTRIES = 'administration/dictionaries/countries',
  ADMINISTRATION_DICTIONARIES_CURRENCIES = 'administration/dictionaries/currencies',
  ADMINISTRATION_DICTIONARIES_EVENTS = 'administration/dictionaries/events',
  ADMINISTRATION_DICTIONARIES_EVENT_DATA_ELEMENTS =
  'administration/dictionaries/event_data_elements',
  ADMINISTRATION_DICTIONARIES_TRANSACTION_TYPES = 'administration/dictionaries/transaction_types',
  ADMINISTRATION_INTERFACES = 'administration/interfaces',
  ADMINISTRATION_INSTITUTIONS = 'administration/institutions',
  ADMINISTRATION_USER = 'administration/permissions/users',
  ADMINISTRATION_USERS_GROUP = 'administration/permissions/user_groups',
  ADMINISTRATION_ENDPOINTS = 'administration/endpoints',
  ADMINISTRATION_SCHEDULER = 'administration/scheduler',
  ADMINISTRATION_SYS_PROPS = 'administration/system_properties',
  ADMINISTRATION_UI_ITEMS_DESIGNER = 'administration/ui_items_designer',
  AUDIT_USER_ACTIVITY = 'audit/users_activity',
  AUDIT_API_CALLS = 'audit/api_calls',
  AUDIT_SCHEDULED_JOBS = 'audit/scheduled_jobs',
  AUDIT_SYSTEM_MONITOR = 'audit/system_monitor',
  AUDIT_UI_SESSIONS = 'audit/ui_sessions',
  LEDGER_ACCOUNTS = 'ledger/accounts',
  LEDGER_CARDS = 'ledger/cards',
  LEDGER_CUSTOMERS = 'ledger/customers',
  LEDGER_MANUAL_TRANSACTIONS = 'ledger/manual_transaction',
  LEDGER_LIMIT_ADJUSTMENT = 'ledger/limit_adjustment',
  LEDGER_TRANSACTIONS = 'ledger/transactions',
  LEDGER_STATEMENTS = 'ledger/statements',
  LEDGER_SETTLE_TRANSACTION = 'ledger/settle_transaction',
  PRODUCT_DESIGNER_PRODUCTS = 'product_designer/products',
}
