export const basePath = '/ui/';

export enum uiItemsConst {
  ACCOUNTS = 'ledger/accounts',
  API_CALLS = 'audit/api_calls',
  CARDS = 'ledger/cards',
  CURRENCY_RATES = 'ledger/currency_rates',
  CUSTOMERS = 'ledger/customers',
  DICTIONARIES_COUNTRIES = 'administration/dictionaries/countries',
  DICTIONARIES_CURRENCIES = 'administration/dictionaries/currencies',
  DICTIONARIES_EVENT_DATA_ELEMENTS = 'administration/dictionaries/event_data_elements',
  DICTIONARIES_EVENTS = 'administration/dictionaries/events',
  DICTIONARIES_TRANSACTION_TYPES = 'administration/dictionaries/transaction_types',
  ENDPOINTS = 'administration/endpoints',
  INSTITUTIONS = 'administration/institutions',
  INTERFACES = 'administration/interfaces',
  LIMIT_ADJUSTMENT = 'ledger/limit_adjustment',
  MANUAL_TRANSACTION = 'ledger/manual_transaction',
  PRODUCTS = 'product_designer/products',
  SCHEDULED_JOBS = 'audit/scheduled_jobs',
  SCHEDULER = 'administration/scheduler',
  SETTLE_TRANSACTION = 'ledger/settle_transaction',
  STATEMENTS = 'ledger/statements',
  SYSTEM_MONITOR = 'audit/system_monitor',
  SYSTEM_PROPERTIES = 'administration/system_properties',
  TRANSACTIONS = 'ledger/transactions',
  UI_SESSIONS = 'audit/ui_sessions',
  USERS = 'administration/permissions/users',
  USERS_ACTIVITY = 'audit/users_activity',
  USERS_GROUPS = 'administration/permissions/user_groups',
}
