import { dateUtil } from 'utils';

export const cronInitialValues = {
  cronSecond: 'cronSecondSpecific',
  cronSecondIncrementIncrement: { value: '1', label: '1' },
  cronSecondIncrementStart: { value: '00', label: '00' },
  cronSecondSpecificSpecific00: true,
  cronSecondRangeStart: { value: '00', label: '00' },
  cronSecondRangeEnd: { value: '00', label: '00' },
  cronMinute: 'cronMinuteSpecific',
  cronMinuteIncrementIncrement: { value: '1', label: '1' },
  cronMinuteIncrementStart: { value: '00', label: '00' },
  cronMinuteSpecificSpecific00: true,
  cronMinuteRangeStart: { value: '00', label: '00' },
  cronMinuteRangeEnd: { value: '00', label: '00' },
  cronHour: 'cronHourSpecific',
  cronHourIncrementIncrement: { value: '1', label: '1' },
  cronHourIncrementStart: { value: '00', label: '00' },
  cronHourSpecificSpecific00: true,
  cronHourRangeStart: { value: '00', label: '00' },
  cronHourRangeEnd: { value: '00', label: '00' },
  cronDay: 'cronEveryDay',
  cronDowIncrementIncrement: { value: '1', label: '1' },
  cronDowIncrementStart: { value: '1', label: 'Sunday' },
  cronDomIncrementIncrement: { value: '1', label: '1' },
  cronDomIncrementStart: { value: '1', label: '1' },
  cronLastSpecificDomDay: { value: '1', label: 'Sunday' },
  cronDaysNearestWeekday: { value: '1', label: '1' },
  cronDaysBeforeEomMinus: { value: '1', label: '1' },
  cronNthDayNth: { value: '1', label: '1' },
  cronNthDayDay: { value: '1', label: 'Sunday' },
  cronMonth: 'cronEveryMonth',
  cronMonthIncrementIncrement: { value: '1', label: '1' },
  cronMonthIncrementStart: { value: '1', label: 'January' },
  cronMonthRangeStart: { value: '1', label: 'January' },
  cronMonthRangeEnd: { value: '1', label: 'January' },
  cronYear: 'cronEveryYear',
  cronYearIncrementIncrement: { value: '1', label: '1' },
  cronYearIncrementStart: {
    value: dateUtil.getCurrentYear(),
    label: dateUtil.getCurrentYear(),
  },
  cronYearRangeStart: {
    value: dateUtil.getCurrentYear(),
    label: dateUtil.getCurrentYear(),
  },
  cronYearRangeEnd: {
    value: dateUtil.getCurrentYear(),
    label: dateUtil.getCurrentYear(),
  },
};
