import { UiItems } from './types';

export const uiItemsData: UiItems = {
  ui_items: [
    {ui_item: 'administration', item_type: 'M'},
    {ui_item: 'administration/cycles', item_type: 'M'},
    {ui_item: 'administration/cycles/cycles_editor', item_type: 'm'},
    {ui_item: 'administration/dictionaries', item_type: 'M'},
    {ui_item: 'administration/dictionaries/countries', item_type: 'm'},
    {ui_item: 'administration/dictionaries/currencies', item_type: 'm'},
    {ui_item: 'administration/dictionaries/events', item_type: 'm'},
    {ui_item: 'administration/dictionaries/event_data_elements', item_type: 'm'},
    {ui_item: 'administration/institutions', item_type: 'm'},
    {ui_item: 'administration/permissions', item_type: 'M'},
    {ui_item: 'administration/permissions/users', item_type: 'm'},
    {ui_item: 'administration/permissions/user_groups', item_type: 'm'},
    {ui_item: 'administration/scheduler', item_type: 'm'},
    {ui_item: 'administration/system_properties', item_type: 'm'},
    {ui_item: 'audit', item_type: 'M'},
    {ui_item: 'audit/api_calls', item_type: 'm'},
    {ui_item: 'audit/scheduled_jobs', item_type: 'm'},
    {ui_item: 'audit/users_activity', item_type: 'm'},
    {ui_item: 'ledger', item_type: 'M'},
    {ui_item: 'ledger/accounts', item_type: 'm'},
    {ui_item: 'ledger/cards', item_type: 'm'},
    {ui_item: 'ledger/customers', item_type: 'm'},
    {ui_item: 'ledger/statements', item_type: 'm'},
    {ui_item: 'ledger/transactions', item_type: 'm'},
    {ui_item: 'product_designer', item_type: 'M'},
    {ui_item: 'product_designer/products', item_type: 'm'},
    {ui_item: 'reports', item_type: 'M'},
    {ui_item: 'reports/customer_statistics', item_type: 'm'},
    {ui_item: 'reports/product_statistics', item_type: 'm'},
    {ui_item: 'reports/transactions_summary', item_type: 'm'},
  ],
};
