import { ICurrencyLimitsData, ICustomersData } from './types';

export const customersMock: ICustomersData = {
  customers: [
    {
      id: 1,
      institution_id: 1,
      first_name: 'John',
      last_name: 'Jones',
      status: 'A',
      date_of_birth: '2019-07-29',
      email: 'test@boxproc.com',
      mobile_phone_number: '+4477712312345',
      address_line1: 'The Holy House',
      address_line2: '1 High street',
      address_line3: 'Essex',
      address_line4: '',
      address_town: 'Bury',
      address_post_code: 'DD99 99DD',
      address_country_code: 'GBR',
      nationality_country_code: 'GBR',
      date_created: '2019-07-29',
      date_closed: '2019-07-29',
      identification_type: 'N',
      identification_number: 1,
      limit_at_customer_level: 0,
    },
    {
      id: 2,
      institution_id: 1,
      first_name: 'Jane',
      last_name: 'Jones',
      status: 'A',
      date_of_birth: '2019-07-29',
      email: 'test@boxproc.com',
      mobile_phone_number: '+4477712312345',
      address_line1: 'The Holy House',
      address_line2: '1 High street',
      address_line3: 'Essex',
      address_line4: '',
      address_town: 'Bury',
      address_post_code: 'DD99 99DD',
      address_country_code: 'GBR',
      nationality_country_code: 'GBR',
      date_created: '2019-07-29',
      date_closed: '2019-07-29',
      identification_type: 'N',
      identification_number: 1,
      limit_at_customer_level: 1,
    },
  ],
};

export const currencyLimitsMock: ICurrencyLimitsData = {
  currency_limits: [
    {
      customer_id: 1,
      currency_numeric_code: 840,
      currency_code: 'USD',
      currency_name: 'United States dollar',
      limit: 100,
    },
    {
      customer_id: 2,
      currency_numeric_code: 971,
      currency_code: 'AFN',
      currency_name: 'Afghan afghani',
      limit: 200,
    },
    {
      customer_id: 3,
      currency_numeric_code: 8,
      currency_code: 'ALL',
      currency_name: 'Albanian lek',
      limit: 300,
    },
    {
      customer_id: 4,
      currency_numeric_code: 51,
      currency_code: 'AMD',
      currency_name: 'Armenian dram',
      limit: 50,
    },
    {
      customer_id: 5,
      currency_numeric_code: 532,
      currency_code: 'ANG',
      currency_name: 'Netherlands Antillean guilder',
      limit: 500,
    },
  ],
};
