import {
  ICurrencyLimitItemData,
  ICustomersData,
  IDirectDebitAccountsData,
  IDirectDebitMandatesData,
} from './types';

export const customersMock: ICustomersData = {
  customers: [
    {
      id: 1,
      institution_id: 1,
      first_name: 'John',
      last_name: 'Jones',
      status: 'A',
      date_of_birth: '2019-07-29',
      email: 'test@boxproc.com',
      mobile_phone_number: '+4477712312345',
      address_line1: 'The Holy House',
      address_line2: '1 High street',
      address_line3: 'Essex',
      address_line4: '',
      address_town: 'Bury',
      address_post_code: 'DD99 99DD',
      address_country_code: 'GBR',
      nationality_country_code: 'GBR',
      date_created: '2019-07-29',
      date_closed: '2019-07-29',
      identification_type: 'N',
      identification_number: 1,
    },
    {
      id: 2,
      institution_id: 1,
      first_name: 'Jane',
      last_name: 'Jones',
      status: 'A',
      date_of_birth: '2019-07-29',
      email: 'test@boxproc.com',
      mobile_phone_number: '+4477712312345',
      address_line1: 'The Holy House',
      address_line2: '1 High street',
      address_line3: 'Essex',
      address_line4: '',
      address_town: 'Bury',
      address_post_code: 'DD99 99DD',
      address_country_code: 'GBR',
      nationality_country_code: 'GBR',
      date_created: '2019-07-29',
      date_closed: '2019-07-29',
      identification_type: 'N',
      identification_number: 1,
    },
  ],
};

export const directDebitAccountsMock: IDirectDebitAccountsData = {
  direct_debit_accounts: [
    {
      id: 1,
      customer_id: 5754,
      provider_account_ref: 'BA0009Y525FAGB',
      provider_customer_ref: 'CU00076KGE0TQZ',
      account_field_1: '11',
      account_field_2: 'BARCLAYS BANK PLC',
      account_field_3: null,
      accountholder_name: 'John Doe',
      country_code: 'GB',
      account_type: null,
      status: 'Active',
      provider_name: 'GoCardless',
    },
    {
      id: 2,
      customer_id: 5754,
      provider_account_ref: 'BA0109Y525FDGB',
      provider_customer_ref: 'CU00076KGE0TQZ',
      account_field_1: '04',
      account_field_2: 'Bank of England',
      account_field_3: null,
      accountholder_name: 'John Doe',
      country_code: 'GB',
      account_type: null,
      status: 'Inactive',
      provider_name: 'GoCardless',
    },
    {
      id: 3,
      customer_id: 5754,
      provider_account_ref: 'BA0009Y525FAGB',
      provider_customer_ref: 'CU00076KGE0TQZ',
      account_field_1: '11',
      account_field_2: 'Barclays Bank',
      account_field_3: null,
      accountholder_name: 'John Doe',
      country_code: 'GB',
      account_type: null,
      status: 'Active',
      provider_name: 'GoCardless',
    },
  ],
};

export const directDebitMandatesMock: IDirectDebitMandatesData = {
  direct_debit_mandates: [
    {
      id: 1,
      customer_id: 5754,
      interface_id: 1,
      provider_customer_ref: 'CU00076KGE0TQZ',
      provider_account_ref: 'BA0109Y525FDGB',
      provider_ref: 'MD0008XXRW3FNG',
      description: 'BOXPROCESSIN-GBJ4Z',
      status: 'Active',
      country_code: 'GB',
      currency_code: 'GBP',
      dd_account_id: 1,
      account_alias: '04',
      last_update_timestamp: '1/06/2020 09:13:00',
      scheme: 'bacs',
    },
    {
      id: 2,
      customer_id: 5754,
      interface_id: 1,
      provider_customer_ref: 'CU00076KGE0TQZ',
      provider_account_ref: 'BA0109Y525FDGB',
      provider_ref: 'MD0008XXRW3FNG',
      description: 'BOXPROCESSIN-GBJ4R',
      status: 'Pending',
      country_code: 'GB',
      currency_code: 'GBP',
      dd_account_id: 1,
      account_alias: '04',
      last_update_timestamp: '25/05/2020 10:54:00',
      scheme: 'bacs',
    },
    {
      id: 3,
      customer_id: 5754,
      interface_id: 1,
      provider_customer_ref: 'CU00076KGE0TQZ',
      provider_account_ref: 'BA0109Y525FDGB',
      provider_ref: 'MD0008XXRW3FNG',
      description: 'BOXPROCESSIN-GBJ4M',
      status: 'Cancelled',
      country_code: 'GB',
      currency_code: 'GBP',
      dd_account_id: 1,
      account_alias: '04',
      last_update_timestamp: '25/05/2020 12:53:00',
      scheme: 'bacs',
    },
  ],
};

export const currencyLimitMock: ICurrencyLimitItemData = {
  currency_limit: [
    {
      base_currency: 840,
      currency_code: 'USD',
      currency_name: 'United States dollar',
      customer_limit: 100,
    },
  ],
};
