import React from 'react';

import { Box } from '@rebass/grid';

import { CircleList, Modal } from 'components';

import { modalNames } from 'consts';

import { CodeForm } from './forms';

interface Register2faModalProps {}

const modalName = modalNames.LOGIN_CODE_2FA_MODAL;

const Register2faModal: React.FC<Register2faModalProps> = () => {
  return (
    <Modal
      title="Enter Second Factor Code"
      name={modalName}
      maxContainerWidth={340}
    >
      <Box mb="7px">
        <CircleList
          items={[
            'Launch Google Authenticator',
            'Enter the code generated by Google Authenticator for BOX UI',
          ]}
        />
      </Box>
      <CodeForm />
    </Modal>
  );
};

export default Register2faModal;
